DROP TABLE IF EXISTS 
T_BNG_MSTR
;


CREATE TABLE IF NOT EXISTS 
T_BNG_MSTR
(

 
CHAR
(
2
)
 
NULL 
COMMENT 
確率設定CD
(BNG_NO
(GM_STTS_CD,PRFMNC_FLG,BNG_NUM,LCH_NUM,KUSN_NTJ,PRFRMNC_CNT_LCH,BNG_MD_CD,BNG_FNSH_NUM,AT_STP_LRS_CD,PRFRMNC_CNT_BNG,HSH,AT_STP_LRS_TM
GM_STTS_CD
 
CHAR
(
1
)
 
NOT NULL 
COMMENT 
ゲーム状態CD
(BNG_
(GM_STTS_CD,PRFMNC_FLG,BNG_NUM,LCH_NUM,KUSN_NTJ,PRFRMNC_CNT_LCH,BNG_MD_CD,BNG_FNSH_NUM,AT_STP_LRS_CD,PRFRMNC_CNT_BNG,HSH,AT_STP_LRS_
END_MSRE
 
CHAR
(
2
)
 
NULL 
COMMENT 
終了マス
(BN
(GM_STTS_CD,PRFMNC_FLG,BNG_NUM,LCH_NUM,KUSN_NTJ,PRFRMNC_CNT_LCH,BNG_MD_CD,BNG_FNSH_NUM,AT_STP_LRS_CD,PRFRMNC_CNT_BNG,HSH,AT_STP_LR
PRFMNC_FLG
 
CHAR
(
1
)
 
NULL 
COMMENT 
演出フラグ
(
(GM_STTS_CD,PRFMNC_FLG,BNG_NUM,LCH_NUM,KUSN_NTJ,PRFRMNC_CNT_LCH,BNG_MD_CD,BNG_FNSH_NUM,AT_STP_LRS_CD,PRFRMNC_CNT_BNG,HSH,AT_STP_
BNG_NUM
 
CHAR
(
2
)
 
NOT NULL 
COMMENT 
ビンゴ回数
(GM_STTS_CD,PRFMNC_FLG,BNG_NUM,LCH_NUM,KUSN_NTJ,PRFRMNC_CNT_LCH,BNG_MD_CD,BNG_FNSH_NUM,AT_STP_LRS_CD,PRFRMNC_CNT_BNG,HSH,AT_ST
BNG_NO
 
CHAR
(
10
)
 
NOT NULL 
COMMENT 
ビンゴ番号
(GM_STTS_CD,PRFMNC_FLG,BNG_NUM,LCH_NUM,KUSN_NTJ,PRFRMNC_CNT_LCH,BNG_MD_CD,BNG_FNSH_NUM,AT_STP_LRS_CD,PRFRMNC_CNT_BNG,HSH,AT_
LCH_NUM
 
CHAR
(
2
)
 
NULL 
COMMENT 
リーチ回数
(GM_STTS_CD,PRFMNC_FLG,BNG_NUM,LCH_NUM,KUSN_NTJ,PRFRMNC_CNT_LCH,BNG_MD_CD,BNG_FNSH_NUM,AT_STP_LRS_CD,PRFRMNC_CNT_BNG,HSH,A
KUSN_NTJ
 
DATE
(
14
)
 
NOT NULL 
COMMENT 
更新日時
(GM_STTS_CD,PRFMNC_FLG,BNG_NUM,LCH_NUM,KUSN_NTJ,PRFRMNC_CNT_LCH,BNG_MD_CD,BNG_FNSH_NUM,AT_STP_LRS_CD,PRFRMNC_CNT_BNG,HSH
FREE_MSRE
 
CHAR
(
2
)
 
NULL 
COMMENT 
Freeマス
(GM_STTS_CD,PRFMNC_FLG,BNG_NUM,LCH_NUM,KUSN_NTJ,PRFRMNC_CNT_LCH,BNG_MD_CD,BNG_FNSH_NUM,AT_STP_LRS_CD,PRFRMNC_CNT_BNG,H
TURK_NTJ
 
DATE
(
14
)
 
NOT NULL 
COMMENT 
登録日時
(GM_STTS_CD,PRFMNC_FLG,BNG_NUM,LCH_NUM,KUSN_NTJ,PRFRMNC_CNT_LCH,BNG_MD_CD,BNG_FNSH_NUM,AT_STP_LRS_CD,PRFRMNC_CNT_BNG
PRFRMNC_CNT_LCH
 
VARCHAR
(
40
)
 
NOT NULL 
COMMENT 
演出回数_リーチ
(GM_STTS_CD,PRFMNC_FLG,BNG_NUM,LCH_NUM,KUSN_NTJ,PRFRMNC_CNT_LCH,BNG_MD_CD,BNG_FNSH_NUM,AT_STP_LRS_CD,PRFRMNC_CNT_B
BNG_MD_CD
 
CHAR
(
1
)
 
NOT NULL 
COMMENT 
ビンゴモードCD
(GM_STTS_CD,PRFMNC_FLG,BNG_NUM,LCH_NUM,KUSN_NTJ,PRFRMNC_CNT_LCH,BNG_MD_CD,BNG_FNSH_NUM,AT_STP_LRS_CD,PRFRMNC_CNT
BNG_FNSH_NUM
 
CHAR
(
2
)
 
NOT NULL 
COMMENT 
ビンゴ終了回数
(GM_STTS_CD,PRFMNC_FLG,BNG_NUM,LCH_NUM,KUSN_NTJ,PRFRMNC_CNT_LCH,BNG_MD_CD,BNG_FNSH_NUM,AT_STP_LRS_CD,PRFRMNC_C
AT_STP_LRS_CD
 
CHAR
(
2
)
 
NULL 
COMMENT 
自動一時停止CD
(GM_STTS_CD,PRFMNC_FLG,BNG_NUM,LCH_NUM,KUSN_NTJ,PRFRMNC_CNT_LCH,BNG_MD_CD,BNG_FNSH_NUM,AT_STP_LRS_CD,PRFRMNC
PRFRMNC_CNT_BNG
 
VARCHAR
(
40
)
 
NOT NULL 
COMMENT 
演出回数_ビンゴ
(GM_STTS_CD,PRFMNC_FLG,BNG_NUM,LCH_NUM,KUSN_NTJ,PRFRMNC_CNT_LCH,BNG_MD_CD,BNG_FNSH_NUM,AT_STP_LRS_CD,PRFRM
HSH
 
VARCHAR
(
80
)
 
NOT NULL 
COMMENT 
ハッシュ
(GM_STTS_CD,PRFMNC_FLG,BNG_NUM,LCH_NUM,KUSN_NTJ,PRFRMNC_CNT_LCH,BNG_MD_CD,BNG_FNSH_NUM,AT_STP_LRS_CD,PRF
AT_STP_LRS_TM
 
INT
(
11
)
 
NULL 
COMMENT 
自動一時停止解除時間
(GM_STTS_CD,PRFMNC_FLG,BNG_NUM,LCH_NUM,KUSN_NTJ,PRFRMNC_CNT_LCH,BNG_MD_CD,BNG_FNSH_NUM,AT_STP_LRS_CD,P
;
